title : ŁW's thoughts on software
tagline:
author :
  name : Łukasz Wiecheć
  email : coquelicot408@gmail.com
  github : lwiechec
  twitter : lwiechec

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

